name: Update issue on P1 label new

on:
  issues:
    types: [labeled]

jobs:
  update_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update issue on P1 label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the event payload
          payload=$(cat $GITHUB_EVENT_PATH)
          
          # Get the label name that was added
          label=$(echo "$payload" | jq -r '.label.name')
          
          # Check if the label is "P1"
          if [[ $label == "P1" ]]; then
            # Get the current issue description
            description=$(echo "$payload" | jq -r '.issue.body')
            
            # Append the autolabeler tag to the description
            new_description="$description\n\nautolabeler:P1"
            
            # Update the issue with the new description
            curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$GITHUB_ISSUE_NUMBER \
              -d "{\"body\":\"$new_description\"}"
          fi