name: Update Issue Description
uses: your-username/your-repo-name@master
with:
  token: ${{ secrets.GITHUB_TOKEN }}
on:
  issues:
    types: [labeled]

jobs:
  update-issue-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if label is present and is "P1"
        if: github.event.label.name == 'P1'
        run: |
          echo "Label 'P1' is present"
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout ${{ github.event.issue.number }}
          echo "\nautolabeler:P1" >> ${{ github.event.issue.body }}
          git commit -am "Update issue description"
          git push